### ISSUE TITLE
Bug : Window is not defined with NextJs

### ISSUE THREAD

**Issue by armandsalle** [aaronhayes/react-use-hubspot-form#10]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hello 👋 I'm using NextJs with SSR. I get `ReferenceError: window is not defined` because of the SSR.
If you can add a check if window is defined before adding scripts it's will be great.

If my explanations are not good, feel free to ask me more detail. And sorry for my English 🇫🇷

**Comment by aaronhayes** [comment]
Try version `1.2.2` :)
