### ISSUE TITLE
Upgrade compatibility to react-^17

### ISSUE THREAD

**Issue by yenicelik** [aaronhayes/react-use-hubspot-form#23]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Currently the peer dependency forbis to install `@aaronhayes/react-use-hubspot-form` from being used in a project that is using react-17.0.2 as it seems to use react-16. Would it be possible to check compatibility with it? Would be incredibly useful, great npm package!

**Comment by aaronhayes** [comment]
Hi @yenicelik, 

I've updated the peer deps version requirements in a new release, could you give `1.2.6` a go and let me know if that solves your problem.

**Comment by aaronhayes** [comment]
I'm going to close this issue, feel free to reopen if it's still a problem.

**Comment by yenicelik** [comment]
wow this was fast. thank you so much!!
