### ISSUE TITLE
Improved typings vs HubSpot free tier

### ISSUE THREAD

**Issue by dsebastien** [aaronhayes/react-use-hubspot-form#3]
Hey there @aaronhayes 

Just to let you know, I've forked your repo to push some changes that I've made on my end while trying to integrate a HubSpot form in my React app.

Your library helped, but unfortunately, I've realized that I'm not able to customize the styling of the rendered form (the settings seem to be ignored by the HubSpot client JS script (??)).

So, just in case you can find the changes I've made here; mostly related to TypeScript typings: https://github.com/dsebastien/react-use-hubspot-form/commit/0173bf14ca6581a55aacf5bf94d05f566608389f

**Comment by aaronhayes** [comment]
Hi @dsebastien, those changes look pretty good, mind making a PR? I'd be happy to merge that in.

**Comment by dsebastien** [comment]
I've sent the PR, but won't be able to follow it up much as I've now switched to ConvertKit.. ;-)
