### ISSUE TITLE
Private apps?

### ISSUE THREAD

**Issue by kb1995** [aaronhayes/react-use-hubspot-form#38]
Hey, I just received a warning from Hubspot that I need to migrate my form submissions over to Private Apps. Given that this hook relates to embedding Hubspot form, I assume that this doesn't impact us. I just want to double-check.

**Comment by aaronhayes** [comment]
I think we are good; I don't really know what private apps are, but they seem completely different features.  https://developers.hubspot.com/docs/api/private-apps 

Thanks @kb1995 :)
